# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "331a9fccc80a810b80f9b38cefcdcaa7"
name = "Xeo Hide Price"
application_url = "https://pricehide-fles.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[webhooks.privacy_compliance]
customer_deletion_url = "https://pricehide-fles.vercel.app/webhooks"
customer_data_request_url = "https://pricehide-fles.vercel.app/webhooks"
shop_deletion_url = "https://pricehide-fles.vercel.app/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,read_themes"

[auth]
redirect_urls = [ "https://pricehide-fles.vercel.app/auth/callback" ]
